accounts/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.index , name='index'),
    
    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
     
    
    path('products/', views.product, name='products'),
    path('customer/<str:pk_test>/', views.customer, name='customer'),
    path('create_order/<str:pk>/', views.createOrder, name='create_order'),
    path('update_order/<str:pk>/', views.updateOrder, name='update_order'),   
    path('delete_order/<str:pk>/', views.deleteOrder, name='delete_order'),   
]

crm1/urls.py
from django.conf.urls import url
from django.urls import include
from django.contrib import admin



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('accounts.urls')),

]

accounts/models.py
from django.db import models

# Create your models here.

class Customer(models.Model):
    name = models.CharField(max_length=255, null=True)
    phone = models.CharField(max_length=255, null=True)
    email = models.EmailField(max_length=255, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    
    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=255, null=True)
    
    def __str__(self):
        return self.name



class Product(models.Model):
    CATEGORY = (
        ('Indoor', 'Indoor'),
        ('Out Door', 'Out Door'),
    )
    name = models.CharField(max_length=255, null=True)
    price = models.FloatField(max_length=255, null=True)
    category = models.CharField(max_length=255, null=True, choices = CATEGORY)
    description = models.CharField(max_length=255, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True) 
    tags = models.ManyToManyField(Tag)


    def __str__(self):
        return self.name



class Order(models.Model):
    STATUS = (
        ('Pending', 'Pending'),
        ('Out for delivery', 'Out for delivery'),
        ('Delivered', 'Delivered'),
    )
    custumer = models.ForeignKey(Customer, null=True, on_delete=models.SET_NULL)
    product =  models.ForeignKey(Product, null=True, on_delete=models.SET_NULL)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    status = models.CharField(max_length=255, null=True, choices = STATUS) 
    note = models.CharField(max_length=255, null=True) 
   
    def __str__(self):
        return self.product.name

accounts/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from .models import Order


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = '__all__'


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
    
    

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.forms import inlineformset_factory 
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from django.contrib import messages

from .models import *
from .forms import *
from .filters import *
# Create your views here.

def registerPage(request):
    if request.user.is_authenticated:
        return redirect('accounts:index')
    else:    
        form = UserCreationForm()
        if request.method == "POST":
            form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account was created for ' + user)
            return redirect('accounts:login') 
    
        context = { 'form':form }
        return render(request, 'accounts/register.html', context)


def loginPage(request):
    if request.user.is_authenticated:
        return redirect('accounts:index')  
    else:    
        if request.method == 'POST':
            username = request.POST.get('username')
            password= request.POST.get('password')

            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('accounts:index')
            else:
                messages.info(request, 'Username Or Password is incorrect.')
        context = {}
        return render(request, 'accounts/login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('accounts:login')


@login_required(login_url='accounts:login')
def index(request):
    orders = Order.objects.all()
    customers = Customer.objects.all()
    
    total_customers = customers.count()
    
    total_orders = orders.count()
    delivered = orders.filter(status='Delivered').count()
    pending = orders.filter(status='Pending').count()
    
    context = { 'orders': orders, 'customers': customers ,
               'total_orders':total_orders, 'delivered': delivered, 'pending':pending}
    
    return render(request, 'accounts/dashbord.html', context)


@login_required(login_url='accounts:login')
def product(request):
    products = Product.objects.all()
    return render(request, 'accounts/product.html', {'products' : products })


@login_required(login_url='accounts:login')
def customer(request, pk_test):
    customer = Customer.objects.get(id=pk_test)
    orders = customer.order_set.all()
    order_count = orders.count() 
    
    myFilter = OrderFilter(request.GET, queryset=orders)
    orders = myFilter.qs
    
    context = { 'customer': customer, 'orders' : orders, 'order_count' : order_count,
               'myFilter':myFilter}
    
    return render(request, 'accounts/customer.html', context)


@login_required(login_url='accounts:login')
def createOrder(request, pk):
    OrderFormSet = inlineformset_factory(Customer, Order, fields=('product',
    'status'), extra=10)
    customer = Customer.objects.get(id=pk)
    # form = OrderForm(initial={'customer':customer})
    formset = OrderFormSet(queryset=Order.objects.none(),instance=customer)
    if request.method == 'POST':
        # form = OrderForm(request.POST)
        formset = OrderFormSet(request.POST , instance=customer)
        if formset.is_valid():
            formset.save()
            return redirect('/')   
         
    context = {'formset' : formset}
    return render(request, 'accounts/order_form.html', context)


@login_required(login_url='accounts:login')
def updateOrder(request, pk):
    order = Order.objects.get(id = pk )
    form = OrderForm(instance=order)
    
    if request.method == 'POST':
        form = OrderForm(request.POST, instance=order)
        if form.is_valid():
            form.save()
            return redirect('/')    
    
    context = { 'form': form }
    return render(request, 'accounts/order_form.html', context)


@login_required(login_url='accounts:login')
def deleteOrder(request, pk):
    order = Order.objects.get(id=pk)
    if request.method == "POST":
        order.delete()
        return redirect('/')
    
    context = {'item': order}
    return render(request, 'accounts/delete.html', context)

crm1/views.py
from django.shortcuts import render



def home(request):
   
    return render(request, 'home.html')

accounts/templates/accounts/customer.html
{% extends 'base.html' %} {% block content %}

<br>

<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <h5>Customer:</h5>
            <hr>
            <a class="btn btn-outline-info 	btn-sm btn-block" href="{% url 'accounts:update_order' customer.id %}">Update Customer</a>
            <a class="btn btn-outline-info  btn-sm btn-block" href="{% url 'accounts:create_order' customer.id %}">Place Order</a>

        </div>
    </div>

    <div class="col-md">
        <div class="card card-body">
            <h5>Contact Information</h5>
            <hr>
            <p>Email: {{ customer.email }} </p>
            <p>Phone: {{ customer.phone }}</p>
        </div>
    </div>

    <div class="col-md">
        <div class="card card-body">
            <h5>Total Orders</h5>
            <hr>
            <h1 style="text-align: center;padding: 10px">{{ order_count }}</h1>
        </div>
    </div>
</div>


<br>
<div class="row">
    <div class="col">
        <div class="card card-body">
            <form method="get">
				{{ myFilter.form }}
                <button class="btn btn-primary" type="submit">Search</button>
            </form>

        </div>
    </div>

</div>
<br>

<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <table class="table table-sm">
                <tr>
                    <th>Product</th>
                    <th>Note</th>
                    <th>Date Orderd</th>
                    <th>Status</th>
                    <th>Update</th>
                    <th>Remove</th>
                </tr>
                {% for order in orders %}

                <tr>
                    <td>{{ order.product }}</td>
                    <td>{{ order.note }}</td>
                    <td>{{ order.date_created }}</td>
					<td>{{ order.status }}</td>
                    <td>
						<a class='btn btn-sm btn-info' href="{% url 'accounts:update_order' order.id %}">Update</a></td>
                    <td>
						<a class='btn btn-sm btn-danger' href="{% url 'accounts:delete_order' order.id %}">Delete</a></td>
                </tr>

                {% endfor %}
            </table>
        </div>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/dashbord.html
{% extends 'base.html' %} 
{% block content %} 

	{% include 'accounts/status.html' %}


<br>

<div class="row">
    <div class="col-md-5">
        <h5>CUSTOMERS:</h5>
        <hr>
        <div class="card card-body">
            <a class="btn btn-primary  btn-sm btn-block" href="">Create Customer</a>
            <table class="table table-sm">
                <tr>
                    <th></th>
                    <th>Customer</th>
                    <th>Phone</th>
                </tr>
                {% for customer in customers %}
                <tr>
					<td><a  
					class='btn btn-sm btn-info'
					href="{% url 'accounts:customer' customer.id %}">View</a></td>
                    <td>{{ customer.name }}</td>
                    <td>{{ customer.phone }}</td>
                </tr>

                {% endfor %}
            </table>
        </div>
    </div>

    <div class="col-md-7">
        <h5>LAST 5 ORDERS</h5>
        <hr>
        <div class="card card-body">
            {% comment %} <a class="btn btn-primary  btn-sm btn-block" href="{% url 'accounts:create_order' customer.id %}">Create Order</a> {% endcomment %}
            <table class="table table-sm">
                <tr>
                    <th>Product</th>
                    <th>Date Orderd</th>
                    <th>Status</th>
                    <th>Update</th>
                    <th>Remove</th>
                </tr>
                {% for order in orders %}
                <tr>
                    <td>{{ order.product }}</td>
                    <td>{{ order.date_created }}</td>
                    <td>{{ order.status }}</td>
                    <td><a class='btn btn-sm btn-info' href="{% url 'accounts:update_order' order.id %}">Update</a></td>
                    <td><a class='btn btn-sm btn-danger' href="{% url 'accounts:delete_order' order.id %}">Delete</a></td>
                </tr>

                {% endfor %}
            </table>
        </div>
    </div>

</div>

{% endblock %}

accounts/templates/accounts/delete.html
{% extends 'base.html' %} {% block content %}

<div class="row">
    <div class="col-md">
        <div class="card card-body">
        <p>Are you sure you want to delete "{{item}}"?</p>

        <form action="{% url 'accounts:delete_order' item.id %}" method="POST">
            {% csrf_token %}
            <a class="btn btn-warning" href="{% url 'accounts:index' %}">Cancel</a>
            <input class="btn btn-danger" type="submit" name="Confirm">
        </form>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
	
{% block content %}

    <div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
                    {% for message in messages %}

                        <p id="messages">{{ message }}</p>

                    {% endfor %}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'accounts:register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>

{% endblock  %}

accounts/templates/accounts/order_form.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <form action="" method="POST">
                {% csrf_token %}
                {{ formset.management_form }}
                {% for form in formset %}
                    {{ form }}
                    <hr>
                {% endfor %}

                <input type="submit" name="submit">
            </form>
        </div>
    </div>
</div>


{% endblock  %}

accounts/templates/accounts/product.html
{% extends 'base.html' %} {% block content %}

<br>

<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <h5>Products</h5>
        </div>
        <div class="card card-body">
            <table class="table">
                <tr>
                    <th>Product</th>
                    <th>Price</th>
                    <th>Category</th>
                </tr>
                {% for i in products %}
                <tr>
                    <td>{{ i.name }}</td>
                    <td>{{ i.price }}</td>
                    <td>{{ i.category }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>

</div>

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}

    <div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
                             {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							    {{ form.username }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{ form.email }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{ form.password1 }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
                            {{ form.password2 }}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>
		
                    {{form.errors}}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'accounts:login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>

{% endblock  %}

accounts/templates/accounts/status.html
<br>


<div class="row">
	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="total-orders">
			  	<div class="card-header">
			  		<h5 class="card-title">Total Orders</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{total_orders}}</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-delivered">
			  	<div class="card-header">
			  		<h5 class="card-title">Orders Delivered</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{delivered}}</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-pending">
			  	<div class="card-header">
			  		<h5 class="card-title">Orders Pending</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{ pending }}</h3>
			  	</div>
			</div>
		</div>
	</div>
</div>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    <link rel="stylesheet" href="{% static '/css/login.css' %}">

</head>

<body>

    {% include 'navbar.html' %} {% block content %} {% endblock %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</body>

</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}

     <a href="{% url 'accounts:index' %}">Dashboard</a> 

{% endblock  %}

templates/navbar.html
{% load static %}

  <style>
    .hello-msg{
      font-size: 18px;
      color: #fff;
      margin-right: 20px;
    }
  </style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <a class="navbar-brand" href="{% url 'accounts:index' %}">Darmanko-dev</a>    
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'accounts:index' %}">Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:products' %}">Products</a>
        </li>
      </ul>
    </div>
  </div>

   <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
            {% else %}
             <li><a href="{% url 'accounts:login' %}">Login</a></li>
              <li><a href="{% url 'accounts:register' %}">Reegister Account</a></li>
            {% endif %}
          </ul>


</nav>